---
- hosts: app_nodes
  become: yes
  vars:
    JRE_RPM_URL: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-al2-jre.rpm
    APP_ARTIFACT_URL: https://github.com/jkanclerz/pp5-voucher-store-12/releases/download/v0.1.1/application.jar
    APP_DIR: /opt/ecommerce
    APP_USER: ecommerce
    APP_PORT: 5000
  tasks:
    - name: "Install jre"
      yum:
        name: "{{ JRE_RPM_URL }}"
        state: present
    - name: "Ensure app dir exists"
      file:
        path: "{{ APP_DIR }}"
        state: directory
    - name: "download app artifact"
      get_url:
        url: "{{APP_ARTIFACT_URL}}"
        dest: "{{ APP_DIR ~ '/application.jar'}}"
    - name: "create user for my app"
      user:
        name: "{{ APP_USER }}"
        state: present
    - name: "place service cfg"
      template:
        src: files/systemd/ecommerce.service
        dest: /etc/systemd/system/ecommerce.service
    - name: "start my app"
      systemd:
        name: ecommerce
        enabled: yes
        state: started
        daemon_reload: yes

- hosts: lb_nodes
  become: yes
  vars:
    DOMAIN_NAME: voucherthief.xd.pl
    DOMAIN_OWNER_EMAIL: grzegorz.floryda@gmail.com
    APP_NODE_IPS: 
      - '172.31.41.102:5000'
    EPEL_RPM_URL: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    CERT_BOT_RPM: https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/c/certbot-1.11.0-1.el7.noarch.rpm
  tasks:
    - name: "install epel"
      yum:
        name: "{{ EPEL_RPM_URL }}"
        state: present
    - name: "install nginx"
      yum:
        name: nginx
        state: present
    - name: "install certbot dep"
      yum:
        name: "{{ CERT_BOT_RPM }}"
        state: present
    - name: "install certbot nginx-plugin"
      yum:
        name: "certbot-nginx"
        state: present
    - name: "put nginx cfg"
      template:
        src: files/nginx/ecommerce.conf
        dest: /etc/nginx/conf.d/ecommerce.conf
    - name: "start nginx"
      systemd:
        name: nginx
        enabled: yes
        state: restarted